seed: 0
optimizer:
  n_agents: 16
  n_max_iterations: 2000
  mutation_probability: 0.2
  mutation_rate: 0.16
env: 
  gravity: 
    # [m / s^2]
    x: 0.0
    # [m / s^2]
    y: 0.0
  domain:
    # [m]
    x_min: -20.0
    # [m]
    x_max: 20.0
    # [m]
    y_min: -20.0
    # [m]
    y_max: 20.0
  box:
    diam: 1.0
    density: 0.5
    friction: 2.0
    init_position: 
      x: 0.0                       # [m]
      y: 0.0                      # [m]
    init_linear_velocity: 
      x: .0                       # [m / s]
      y: .0                     # [m / s]
    init_angular_velocity: 0.0            # [rad / s]
    init_angle: 0.0                   # deg 
    ray_length: 60
    noise: 
      position: 
        x: 0.001                       # Standard deviation [m]
        y: 0.001                       # Standard deviation [m]
      linear_velocity: 
        x: .0                        # Standard deviation [m / s]
        y: .0                        # Standard deviation [m / s]
      angular_velocity: 0.0             # Standard deviation [rad / s]
      angle: 0.0                      # Standard deviation [deg]
    engine:
      max_force: 10.0
    neural_network:
      n_dim_in: 8      # x- and y-coordinates of detected obstacles.
      n_dim_out: 4     # Actions for four engines.
      n_dim_hidden: 32  # Hidden dimensions.
      n_hidden: 2   # Hidden layer.

renderer:
  scale_force: 1.0