# SpaceDrones configuration file
#
# At the moment the following parameters aren't changeable:
#
#   - allow_collision_drones
#   - num_dim_in
#   - num_dim_out
#
random_seed: 122333

dirs:
  frames: "frames"

checkpoints:
  load_model: false
  save_model: false
  model_path: "weights"

optimizer:
  num_agents: 8
  num_max_steps: 1000
  mutation_probability: 0.05
  mutation_rate: 0.04
  # mllib: "numpy"    # numpy, torch

env: 
  allow_collision_drones: false   # do not change
  allow_collision_domain: true

  gravity: 
    x: 0.0
    y: 0.0

  domain:
    limit:
      x_min: -20.0
      x_max: 20.0
      y_min: -20.0
      y_max: 20.0
    map: "block"  # empty, block, track, locks, blade, smile

  drone:
    fixed_rotation: true
    diam: 1.0
    density: 1.0
    friction: 5.0

    engine:
      max_force: 10.0
      density: 1.0
      friction: 5.0

    # kinematics:
    #   init_position:
    #     x: -1
    #     y: -1

    init_position: 
      x: 12.0
      y: 12.0
    init_linear_velocity: 
      x: 0.0
      y: 0.0
    init_angular_velocity: 0.0
    init_angle: 0.0

    raycasting:
      ray_length: 60

    neural_network: # model
      num_dim_in: 8       # Distances to the nearest wall.
      num_dim_out: 4      # Actions for four engines.
      num_dim_hidden: 32
      num_hidden_layers: 2

    respawn:
      is_random: false

framework:
  screen:
    width: 640
    height: 640
  target_fps: 60
  velocity_iterations: 10   # Number of iterations to compute next velocity.
  position_iterations: 10   # Number of iterations to compute next position.

renderer:
  scale_force: 0.5
  ppm: 15     # Pixels per meter / zoom