# SpaceDrones configuration
name: "SpaceDrones"
random_seed: 4171250

# Directory to save frames to create video.
dirs:
  frames: "frames"

checkpoints:
  load_model: false
  save_model: false 
  model_path: "weights"
  model_name: "1"  # save / load

optimizer:
  name: "ces"  # ces, nes, evo
  evo:
    mutation_probability: 0.04
    mutation_rate: 0.02
  nes:
    learning_rate: 0.04
    sigma: 0.1
  ces:
    learning_rate: 0.0001
    sigma: 0.1
    momentum: 0.01
  num_agents: 1
  num_max_steps: 2000
  reward:
    distance: false
    distance_to_target: true

env: 
  allow_collision_domain: false

  gravity: 
    x: 0.0
    y: 0.0

  domain:
    limit:
      x_min: -20.0
      x_max: 20.0
      y_min: -20.0
      y_max: 20.0
    map: "empty"  # empty, block, track, locks, blade, smile

  snitch:
    move_every_n_steps: 400

  drone:
    diam: 1.0
    density: 1.0
    friction: 5.0

    engine:
      max_force: 10.0
      density: 1.0
      friction: 5.0

    init_position: 
      x: 15.0
      y: -15.0
    init_linear_velocity: 
      x: 0.0
      y: 0.0
    init_angular_velocity: 0.0
    init_angle: 0.0

    neural_network: # model
      num_dim_in: 14  # Distances to the nearest wall, position, velocity, position of target.
      num_dim_out: 4  # Actions for four engines.
      num_dim_hidden: 16
      num_hidden_layers: 2
      nonlinearity: "tanh"  # relu, tanh

    raycasting:
      ray_length: 60

    respawn:
      is_random: true 
      is_all_random: false

framework:
  screen:
    width: 640
    height: 640

renderer:
  scale_force: 0.5
  ppm: 15     # Pixels per meter / zoom