random_seed: 122333

checkpoints:
  load_model: false
  save_model: false
  model_path: "weights"

optimizer:
  num_agents: 4
  num_max_steps: 2000
  mutation_probability: 0.05
  mutation_rate: 0.05
  # lib: "numpy"    # numpy, torch

env: 
  allow_collision: false
  # allow_sleep: false

  gravity: 
    x: 0.0
    y: 0.0

  domain:
    limit:
      x_min: -20.0
      x_max: 20.0
      y_min: -20.0
      y_max: 20.0
    map: "block"  # empty, block, cross, track

  drone:
    fixed_rotation: true
    diam: 1.0
    density: 0.5
    friction: 5.0

    # kinematics:
    #   init_position:
    #     x: -1
    #     y: -1

    init_position: 
      x: 5.0
      y: 10.0
    init_linear_velocity: 
      x: 0.0
      y: 0.0
    init_angular_velocity: 0.0
    init_angle: 0.0

    noise:
      add_noise: false
      position: 
        x: 0.9
        y: 0.9 

    raycasting:
      alignment: "diagonal"   # orthogonal, diagonal
      ray_length: 60

    engine:
      density: 0.5
      friction: 5.0
      max_force: 10.0

    neural_network: # model
      num_dim_in: 4     # Distances to the nearest wall.
      num_dim_out: 4  # Actions for four engines.
      num_dim_hidden: 16  
      num_hidden_layers: 2

framework:
  screen:
    width: 640
    height: 640
  target_fps: 60
  velocity_iterations: 10   # Number of iterations to compute next velocity.
  position_iterations: 10   # Number of iterations to compute next position.

renderer:
  scale_force: 0.5
  ppm: 15     # Pixels per meter / zoom