random_seed: 122333

optimizer:
  num_agents: 16
  num_max_steps: 1000
  mutation_probability: 0.2
  mutation_rate: 0.16

env: 
  allow_collision: false

  gravity: 
    x: 0.0
    y: 0.0

  domain:
    limit:
      x_min: -20.0
      x_max: 20.0
      y_min: -20.0
      y_max: 20.0
    obstacle:
      horizontal_bar: true

  drone:
    fixed_rotation: true
    diam: 1.0
    density: 1.0
    friction: 2.0
    init_position: 
      x: 0.0                       # [m]
      y: 0.0                      # [m]
    init_linear_velocity: 
      x: .0                       # [m / s]
      y: .0                     # [m / s]
    init_angular_velocity: 0.0            # [rad / s]
    init_angle: 0.0                   # deg 
    ray_length: 60
    noise: 
      position: 
        x: 0.9
        y: 0.9 
      linear_velocity: 
        x: 0.                        # Standard deviation [m / s]
        y: 0.                        # Standard deviation [m / s]
      angular_velocity: 0.0             # Standard deviation [rad / s]
      angle: 0.0                      # Standard deviation [deg]
    engine:
      density: 1.0
      friction: 2.0
      max_force: 4.0

    neural_network: # model
      num_dim_in: 4     # Distances to the nearest wall.
      num_dim_out: 4  # Actions for four engines.
      num_dim_hidden: 32  # Hidden dimensions.
      num_hidden: 2   # Hidden layer.

renderer:
  scale_force: 1.0