random_seed: 42

# Directory to save frames to create video.
dirs:
  frames: "frames"

checkpoints:
  load_model: false
  save_model: true
  model_path: "weights"
  model_name: "ckpt"  # save / load

optimizer:
  name: "nes"  # ces, nes, evo
  evo:
    mutation_probability: 0.04
    mutation_rate: 0.02
  nes:
    learning_rate: 0.06
    sigma: 0.1
  ces:
    learning_rate: 0.00006
    sigma: 0.1
    momentum: 0.16
  num_agents: 32
  num_max_steps: 500

env: 
  allow_collision_domain: false

  domain:
    limit:
      x_min: -20.0
      x_max: 20.0
      y_min: -20.0
      y_max: 20.0

  track: "static"  # static, random 

  drone:
    diam: 1.0
    density: 1.0
    friction: 5.0

    engine:
      max_force: 20.0
      density: 1.0
      friction: 5.0

    init_position: 
      x: 0.0
      y: 0.0
    init_linear_velocity: 
      x: 0.0
      y: 0.0
    init_angular_velocity: 0.0
    init_angle: 0.0

    neural_network: # model
      num_dim_in: 14  # Distances to the nearest wall, position, velocity, position of next gate.
      num_dim_out: 4  # Actions for four engines.
      num_dim_hidden: 16
      num_hidden_layers: 2
      nonlinearity: "tanh"  # relu, tanh

    raycasting:
      ray_length: 50

    respawn: "random"  # random, all_random, static

framework:
  screen:
    width: 640
    height: 640

renderer:
  scale_force: 0.2
  ppm: 15     # Pixels per meter / zoom
