# SpaceDrones configuration
name: "SpaceDrones"
random_seed: 192837465

# Directory to save frames to create video.
dirs:
  frames: "frames"

checkpoints:
  load_model: false
  save_model: true
  model_path: "weights"
  model_name: "model"  # save / load

optimizer:
  name: "nes"  # nes, evo
  evo:
    mutation_probability: 0.04
    mutation_rate: 0.02
  nes:
    learning_rate: 0.001
    sigma: 0.1
  num_agents: 16
  num_max_steps: 2000
  reward:
    distance: false
    distance_to_target: true

env: 
  allow_collision_domain: false

  gravity: 
    x: 0.0
    y: 0.0

  domain:
    limit:
      x_min: -20.0
      x_max: 20.0
      y_min: -20.0
      y_max: 20.0
    map: "empty"  # empty, block, track, locks, blade, smile

  snitch:
    move_every_n_steps: 250

  drone:
    fixed_rotation: true  # TODO
    diam: 1.0
    density: 1.0
    friction: 5.0

    engine:
      max_force: 10.0
      density: 1.0
      friction: 5.0

    init_position: 
      x: 15.0
      y: -15.0
    init_linear_velocity: 
      x: 0.0
      y: 0.0
    init_angular_velocity: 0.0
    init_angle: 0.0

    neural_network: # model
      num_dim_in: 14       # Distances to the nearest wall, position, velocity, position of target   # TODO
      num_dim_out: 4      # Actions for four engines.  # TODO
      num_dim_hidden: 16
      num_hidden_layers: 2
      nonlinearity: "tanh"  # relu, tanh

    raycasting:
      ray_length: 60

    respawn:
      is_random: true 
      is_all_random: false

framework:
  screen:
    width: 640
    height: 640
  target_fps: 60
  velocity_iterations: 10   # Number of iterations to compute next velocity.
  position_iterations: 10   # Number of iterations to compute next position.

renderer:
  scale_force: 0.5
  ppm: 15     # Pixels per meter / zoom