random_seed: 122333

optimizer:
  num_agents: 4
  num_max_steps: 1000
  mutation_probability: 0.05
  mutation_rate: 0.05

env: 
  allow_collision: false

  gravity: 
    x: 0.0
    y: 0.0

  domain:
    limit:
      x_min: -20.0
      x_max: 20.0
      y_min: -15.0
      y_max: 15.0
    map: "cross"  # empty, cross, track 

  drone:
    fixed_rotation: true
    diam: 1.0
    density: 1.0
    friction: 2.0
    init_position: 
      x: 15.0
      y: -10.0
    init_linear_velocity: 
      x: 0.0
      y: 0.0
    init_angular_velocity: 0.0
    init_angle: 0.0
    ray_length: 60

    noise:
      add_noise: false
      position: 
        x: 0.9
        y: 0.9 

    engine:
      density: 1.0
      friction: 2.0
      max_force: 5.0

    neural_network: # model
      num_dim_in: 4     # Distances to the nearest wall.
      num_dim_out: 4  # Actions for four engines.
      num_dim_hidden: 128  # Hidden dimensions.
      num_hidden: 2   # Hidden layer.

# Danger Zone
# Do not change these settings unless you know what you are doing.
framework:
  screen:
    width: 640
    height: 640
  target_fps: 60
  velocity_iterations: 10   # Number of iterations to compute next velocity.
  position_iterations: 10   # Number of iterations to compute next position.

renderer:
  scale_force: 1.0